dist: bionic

language: go

go:
  - 1.12.x
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
  - travis_retry make dependencies

script:
  - make install-dev-deps
  - make check-style
  - make test

matrix:
  fast_finish: true

notifications:
  email: false
